name: eventaction
#when this work flow should be executed
#on: workflow_dispatch #manually triggered
#what should be done
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*' #dev-ping, dev-oo-oioo
      - 'feature/**' #feature/jun, feature/jun/juue/kk
    paths: 
      - '*.json'
    paths-ignore:
      - '.github/workflows/*'
    
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: print goodbye
        run: echo "good bye"
